version: "3.7"



services:

  nginx:
    image: nginx
    depends_on:
      - webapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/var/www/html
      - ./nginx/data/swagger-docs:/var/www/html/swagger-docs
    
    ports: 
      - 8080:8080

  
    

  webapi:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    volumes:
        - ./images:/app/wwwroot/images
    environment:
       ASPNETCORE_ENVIRONMENT: Production
       ASPNETCORE_URLS: http://+:80
      
    ports:
      - 80
    restart: always
    
  

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/usr/sbin/mysql
    environment:          
        MYSQL_ROOT_PASSWORD: # (2)
              - super_secret
        MYSQL_DATABASE: Shop_DB
    ports:
      - 3306:3306
         
  secrets: # (1)
  super_secret:
    file: ./my-little-secret.txt
           
          

       
