services:

  nginx:
    image: nginx
    depends_on:
      - webapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/var/www/html
      - ./nginx/data/swagger-docs:/var/www/html/swagger-docs
    
    ports: 
      - 8080:8080

  
    

  webapi:
    depends_on:
      - db2
    build:
      context: .
      dockerfile: dockerfile
    volumes:
        - ./images:/app/wwwroot/images
    environment:
       ASPNETCORE_ENVIRONMENT: Production
       ASPNETCORE_URLS: http://+:84
      
    ports:
      - 84
    restart: always
    
 

  db2:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/usr/sbin/mysql
      
    environment:   
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        
        # cm file .emv
   
    ports:
      - 3306:3306
         
 
           
          

       
